# Generated by Django 3.1.4 on 2020-12-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myheader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
