# Generated by Django 3.1.4 on 2020-12-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('details_message', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
