# Generated by Django 3.1.4 on 2020-12-14 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactteam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactteam',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='contactteam',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
