# Generated by Django 3.1.4 on 2020-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201211_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('gaming', 'gaming'), ('food_making', 'food_making'), ('film_making', 'film_making')], max_length=255),
        ),
    ]
